2024-11-04 14:30:25.456 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 30040...
2024-11-04 14:30:25.458 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-11-04 14:30:25.464 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 178
2024-11-04 14:30:25.480 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-11-04 14:30:25.481 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture.il
2024-11-04 14:30:25.481 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-11-04 14:30:25.485 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture
2024-11-04 14:30:25.486 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-11-04 14:30:25.487 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-11-04 14:30:25.488 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-11-04 14:30:25.489 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
2024-11-04 14:30:25.489 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-11-04 14:30:25.490 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
2024-11-04 14:30:25.490 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-11-04 14:30:25.491 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-11-04 14:30:25.829 - INFO    - MainThread - ibstore_insync.py:2754 [connectAsync] - Synchronization complete
2024-11-04 14:30:32.460 - ERROR   - MainThread - decoder.py:200 [interpret] - Error handling fields: ['17', '6', '20161229 11:00:00 US/Eastern', '20161230 11:00:00 US/Eastern', '14', '20161230 04:00:00 US/Eastern', '38.45', '39.00', '38.45', '39.00', '-1', '-1', '-1', '20161230 04:30:00 US/Eastern', '39.00', '39.20', '38.52', '39.20', '-1', '-1', '-1', '20161230 05:00:00 US/Eastern', '39.20', '39.24', '38.52', '39.05', '-1', '-1', '-1', '20161230 05:30:00 US/Eastern', '39.05', '39.20', '38.52', '38.52', '-1', '-1', '-1', '20161230 06:00:00 US/Eastern', '38.52', '39.01', '38.52', '38.52', '-1', '-1', '-1', '20161230 06:30:00 US/Eastern', '38.52', '39.08', '38.52', '39.07', '-1', '-1', '-1', '20161230 07:00:00 US/Eastern', '39.07', '39.10', '39.00', '39.00', '-1', '-1', '-1', '20161230 07:30:00 US/Eastern', '39.00', '39.03', '39.00', '39.00', '-1', '-1', '-1', '20161230 08:00:00 US/Eastern', '39.00', '39.02', '39.00', '39.00', '-1', '-1', '-1', '20161230 08:30:00 US/Eastern', '39.00', '39.02', '39.00', '39.02', '-1', '-1', '-1', '20161230 09:00:00 US/Eastern', '39.02', '39.17', '39.02', '39.13', '-1', '-1', '-1', '20161230 09:30:00 US/Eastern', '39.13', '39.13', '38.70', '38.75', '-1', '-1', '-1', '20161230 10:00:00 US/Eastern', '38.75', '38.84', '38.70', '38.80', '-1', '-1', '-1', '20161230 10:30:00 US/Eastern', '38.80', '38.85', '38.72', '38.77', '-1', '-1', '-1']
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 198, in interpret
    handler(fields)
    ~~~~~~~^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 476, in historicalData
    self.wrapper.historicalDataEnd(int(reqId), startDateStr, endDateStr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 646, in historicalDataEnd
    fromDate = bars[0].date
               ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-11-04 14:30:37.841 - ERROR   - MainThread - decoder.py:200 [interpret] - Error handling fields: ['17', '8', '20161229 11:00:00 US/Eastern', '20161230 11:00:00 US/Eastern', '14', '20161230 04:00:00 US/Eastern', '42.00', '42.00', '39.37', '39.90', '-1', '-1', '-1', '20161230 04:30:00 US/Eastern', '39.90', '40.29', '39.34', '39.90', '-1', '-1', '-1', '20161230 05:00:00 US/Eastern', '39.90', '39.90', '39.90', '39.90', '-1', '-1', '-1', '20161230 05:30:00 US/Eastern', '39.90', '39.90', '39.90', '39.90', '-1', '-1', '-1', '20161230 06:00:00 US/Eastern', '39.90', '39.90', '39.85', '39.85', '-1', '-1', '-1', '20161230 06:30:00 US/Eastern', '39.85', '40.10', '39.50', '39.50', '-1', '-1', '-1', '20161230 07:00:00 US/Eastern', '39.50', '39.50', '39.50', '39.50', '-1', '-1', '-1', '20161230 07:30:00 US/Eastern', '39.50', '39.50', '39.43', '39.50', '-1', '-1', '-1', '20161230 08:00:00 US/Eastern', '39.50', '39.50', '39.33', '39.33', '-1', '-1', '-1', '20161230 08:30:00 US/Eastern', '39.33', '39.33', '39.32', '39.33', '-1', '-1', '-1', '20161230 09:00:00 US/Eastern', '39.33', '39.33', '39.15', '39.31', '-1', '-1', '-1', '20161230 09:30:00 US/Eastern', '39.31', '39.31', '38.76', '38.80', '-1', '-1', '-1', '20161230 10:00:00 US/Eastern', '38.80', '38.88', '38.74', '38.82', '-1', '-1', '-1', '20161230 10:30:00 US/Eastern', '38.82', '38.87', '38.74', '38.81', '-1', '-1', '-1']
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 198, in interpret
    handler(fields)
    ~~~~~~~^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 476, in historicalData
    self.wrapper.historicalDataEnd(int(reqId), startDateStr, endDateStr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 646, in historicalDataEnd
    fromDate = bars[0].date
               ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
