2024-11-01 09:21:44.685 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 47642...
2024-11-01 09:21:44.687 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-11-01 09:21:44.694 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 178
2024-11-01 09:21:44.702 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-11-01 09:21:44.704 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-11-01 09:21:44.705 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-11-01 09:21:44.707 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-11-01 09:21:44.707 - ERROR   - MainThread - decoder.py:189 [handler] - Error for managedAccounts:
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 291, in managedAccounts
    self.ib.managedAccounts(accountsList)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: IBStoreInsync.managedAccounts() takes 1 positional argument but 2 were given
2024-11-01 09:21:44.711 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-11-01 09:21:44.712 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
2024-11-01 09:21:44.713 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-11-01 09:21:44.713 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
2024-11-01 09:21:44.713 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-11-01 09:21:44.714 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-11-01 09:21:45.127 - INFO    - MainThread - ibstore_insync.py:2722 [connectAsync] - Synchronization complete
2024-11-01 09:21:50.185 - ERROR   - MainThread - decoder.py:189 [handler] - Error for contractDetailsEnd:
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 594, in contractDetailsEnd
    self.ib.contractDetailsEnd(reqId)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstore_insync.py", line 481, in contractDetailsEnd
    self.cancelQueue(self.qs[reqId], True)
                     ~~~~~~~^^^^^^^
KeyError: 3
