2024-11-01 13:18:07.679 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 18247...
2024-11-01 13:18:07.681 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-11-01 13:18:07.684 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 178
2024-11-01 13:18:13.586 - ERROR   - MainThread - decoder.py:189 [handler] - Error for managedAccounts:
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 292, in managedAccounts
    self.ib.managedAccounts(accountsList)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: IBStoreInsync.managedAccounts() takes 1 positional argument but 2 were given
2024-11-01 13:18:13.596 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-11-01 13:18:13.597 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-11-01 13:18:13.597 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-11-01 13:18:13.598 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-11-01 13:18:13.598 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-11-01 13:18:13.599 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-11-01 13:18:13.599 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-11-01 13:18:13.600 - INFO    - MainThread - client.py:230 [disconnect] - Disconnecting
2024-11-01 13:18:13.600 - ERROR   - MainThread - client.py:222 [connectAsync] - API connection failed: TimeoutError()
2024-11-01 13:18:13.600 - INFO    - MainThread - client.py:368 [_onSocketDisconnected] - Disconnected.
